# typed: false
# frozen_string_literal: true

# Generated by infra/tap.ts on every release. Edits here are overwritten.
class Rankme < Formula
  desc "Rank yourself as a coder, from the AI coding sessions already on this machine"
  homepage "https://builder-production-5049.up.railway.app"
  version "0.1.4"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/jatinjain25/paxel-dist/releases/download/v0.1.4/builder-darwin-arm64"
      sha256 "c05143908bda97e0d3defbded6ba4b1cd3602cfcd3b382b78f04ad9422eb6df1"
    end
    on_intel do
      url "https://github.com/jatinjain25/paxel-dist/releases/download/v0.1.4/builder-darwin-x64"
      sha256 "2821be85e4545ebdb76e2d3b5a3362d58a95b7a56cd7c7dac346b7bdf4512e33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jatinjain25/paxel-dist/releases/download/v0.1.4/builder-linux-arm64"
      sha256 "b91e5c52c4ae6e9da5d51356b8b4ff98bbeb690979db9880fd349e940d1b4651"
    end
    on_intel do
      url "https://github.com/jatinjain25/paxel-dist/releases/download/v0.1.4/builder-linux-x64"
      sha256 "538ed36ad740adf704006a7c1073ba90e0eba2aaabcbde825bfa74436080c232"
    end
  end

  def install
    # libexec, not bin. The curl installer puts its own `builder` in
    # ~/.local/bin, and a second one earlier on PATH from a different release is
    # how two copies end up disagreeing about what `builder status` says.
    # Only `rankme` is exposed.
    # Whatever single file was staged, rather than a name.
    #
    # Homebrew names the staged file from the URL's basename, but it names the
    # CACHED copy rankme--<version>, and the two are not the same code path.
    # Guessing wrong makes Dir[] empty and install fails on nil -- after the
    # download, in front of the user. The staging directory holds exactly one
    # file for an uncompressed download, so take that one and stop asserting
    # what it is called.
    libexec.install Dir["*"].find { |f| File.file?(f) } => "builder"

    # --api is PREPENDED, so a deliberate --api later on the command line still
    # wins: the parser keeps the last value for an option. It is passed at all
    # because nothing in the brew path ever ran the installer's exec, which is
    # the only other thing that records where to publish.
    (bin/"rankme").write <<~SH
      #!/bin/sh
      # rankme: installed by the homebrew tap
      set -eu
      BUILDER_INVOKED_AS=rankme
      export BUILDER_INVOKED_AS
      case "${1:-}" in ""|-*) set -- publish "$@" ;; esac
      exec "#{libexec}/builder" --api "https://builder-production-5049.up.railway.app" "$@"
    SH
    chmod 0755, bin/"rankme"
  end

  def caveats
    <<~TEXT
      rankme asks before it publishes anything, and that question is read from a
      real terminal. Run it from a shell - not from CI, and not from a coding
      agent's shell tool, which has no controlling terminal and will be refused.

      This formula ships a prebuilt binary and compiles nothing, but Homebrew
      has no bottle for it and so treats installing it as a source build, which
      requires current Command Line Tools. If the install refused with "Your
      Command Line Tools are too outdated", update them - or skip Homebrew
      entirely and use the one-line installer, which needs none of this.
    TEXT
  end

  test do
    assert_match "rankme", shell_output("#{bin}/rankme --help")
  end
end
